apiVersion: v1
kind: Service
metadata:
  labels:
    app: wonderful
  name: wonderful
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wonderful
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}